version: '2'
services:
  webui:
    image: himanshu/dockercoins-webui:$IMAGE_TAG
    links:
    - redis:redis
    ports:
    - 80
    labels:
      io.rancher.container.pull_image: always
  rng:
    image: addteq/dockercoins-rng
    labels:
      io.rancher.container.pull_image: always
  worker:
    image: addteq/dockercoins-worker
    links:
    - rng:rng
    - hasher:hasher
    - redis:redis
    labels:
      io.rancher.container.pull_image: always
  redis:
    image: redis
    labels:
      io.rancher.container.pull_image: always
  hasher:
    image: addteq/dockercoins-hasher
    labels:
      io.rancher.container.pull_image: always
